version: "3"

services:
    jce_java:
        build: ./docker-jce-jre
        image: avail/jce-java
        read_only: true
        command: echo "jce java"
        environment:
            - TZ=Asia/Shanghai
    gateway:
        build: ./api-gateway-ms
        image: avail/gateway-ms
        ports:
            - "7291:7291"
            - "10211:10211"
        depends_on:
            - 'jce_java'
        environment:
            - TZ=Asia/Shanghai