version: "3"

services:
    gitlab:
        image: daocloud.io/daocloud/gitlab:8.16.7-ce.0
        deploy:
          resources:
            limits:
              memory: 256M
            reservations:
              memory: 64M
        ports:
            - "10222:22"
            - "80:80"
            - "10443:443"
        volumes:
            - "./docker-gitlab/config/:/etc/gitlab/"
            - "./docker-gitlab/logs/:/var/log/gitlab/"
            - "./docker-gitlab/data/:/var/opt/gitlab/"
        environment:
            - TZ=Asia/Shanghai
